# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.5.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class UserCreationModeEnum(str, Enum):
    """
    * `never_create` - Never Create * `create_when_required` - Create When Required * `always_create` - Always Create
    """

    """
    allowed enum values
    """
    NEVER_CREATE = 'never_create'
    CREATE_WHEN_REQUIRED = 'create_when_required'
    ALWAYS_CREATE = 'always_create'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserCreationModeEnum from a JSON string"""
        return cls(json.loads(json_str))


