import os

from dotenv import load_dotenv

load_dotenv()

API_V0_STR = "/api/v0"
SECRET_KEY = os.getenv("SECRET_KEY")
PROJECT_NAME = os.getenv("PROJECT_NAME", default="bioterm API")

POSTGRES_SERVER = os.getenv("POSTGRES_SERVER", default="timescaledb:5432")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
SQLALCHEMY_DATABASE_URI = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}/{POSTGRES_DB}"
)

GF_SECURITY_ADMIN_USERNAME = os.getenv("GF_SECURITY_ADMIN_USERNAME", "admin")
GF_SECURITY_ADMIN_PASSWORD = os.getenv("GF_SECURITY_ADMIN_PASSWORD")
GF_SERVER_DOMAIN = os.getenv("GF_SERVER_DOMAIN")
GF_SERVER_ROOT_URL = os.getenv("GF_SERVER_ROOT_URL")

AUTHENTIK_CLIENT_ID = os.getenv("AUTHENTIK_CLIENT_ID")
AUTHENTKIK_CLIENT_SECRET = os.getenv("AUTHENTKIK_CLIENT_SECRET")
AUTHENTIK_URL = os.getenv("AUTHENTIK_URL")
AUTHENTIK_ISSUER = os.getenv("AUTHENTIK_ISSUER")
AUTHENTIK_PUBLIC_KEY = os.getenv("AUTHENTIK_PUBLIC_KEY")
if AUTHENTIK_PUBLIC_KEY:
    AUTHENTIK_PUBLIC_KEY = AUTHENTIK_PUBLIC_KEY.replace("\\n", "\n")

REDIS_SERVER = os.getenv("REDIS_SERVER", default="bioterm-redis")
REDIS_PORT = os.getenv("REDIS_PORT", default="6379")
REDIS_URL = f"redis://{REDIS_SERVER}:{REDIS_PORT}"
