# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
from grafanaApiClient.models.annotation_query import AnnotationQuery
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AnnotationEvent(BaseModel):
    """
    AnnotationEvent
    """ # noqa: E501
    color: Optional[StrictStr] = None
    dashboard_id: Optional[StrictInt] = Field(default=None, alias="dashboardId")
    id: Optional[StrictInt] = None
    is_region: Optional[StrictBool] = Field(default=None, alias="isRegion")
    panel_id: Optional[StrictInt] = Field(default=None, alias="panelId")
    source: Optional[AnnotationQuery] = None
    tags: Optional[List[StrictStr]] = None
    text: Optional[StrictStr] = None
    time: Optional[StrictInt] = None
    time_end: Optional[StrictInt] = Field(default=None, alias="timeEnd")
    __properties: ClassVar[List[str]] = ["color", "dashboardId", "id", "isRegion", "panelId", "source", "tags", "text", "time", "timeEnd"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnnotationEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AnnotationEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "color": obj.get("color"),
            "dashboardId": obj.get("dashboardId"),
            "id": obj.get("id"),
            "isRegion": obj.get("isRegion"),
            "panelId": obj.get("panelId"),
            "source": AnnotationQuery.from_dict(obj.get("source")) if obj.get("source") is not None else None,
            "tags": obj.get("tags"),
            "text": obj.get("text"),
            "time": obj.get("time"),
            "timeEnd": obj.get("timeEnd")
        })
        return _obj


