# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr, field_validator
from pydantic import Field
from grafanaApiClient.models.calculate_diff_target import CalculateDiffTarget
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CalculateDashboardDiffRequest(BaseModel):
    """
    CalculateDashboardDiffRequest
    """ # noqa: E501
    base: Optional[CalculateDiffTarget] = None
    diff_type: Optional[StrictStr] = Field(default=None, description="The type of diff to return Description: `basic` `json`", alias="diffType")
    new: Optional[CalculateDiffTarget] = None
    __properties: ClassVar[List[str]] = ["base", "diffType", "new"]

    @field_validator('diff_type')
    def diff_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('basic', 'json'):
            raise ValueError("must be one of enum values ('basic', 'json')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CalculateDashboardDiffRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base
        if self.base:
            _dict['base'] = self.base.to_dict()
        # override the default output from pydantic by calling `to_dict()` of new
        if self.new:
            _dict['new'] = self.new.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CalculateDashboardDiffRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "base": CalculateDiffTarget.from_dict(obj.get("base")) if obj.get("base") is not None else None,
            "diffType": obj.get("diffType"),
            "new": CalculateDiffTarget.from_dict(obj.get("new")) if obj.get("new") is not None else None
        })
        return _obj


