# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
from grafanaApiClient.models.url import URL
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ProxyConfig(BaseModel):
    """
    ProxyConfig
    """ # noqa: E501
    no_proxy: Optional[StrictStr] = Field(default=None, description="NoProxy contains addresses that should not use a proxy.")
    proxy_connect_header: Optional[Dict[str, List[StrictStr]]] = None
    proxy_from_environment: Optional[StrictBool] = Field(default=None, description="ProxyFromEnvironment makes use of net/http ProxyFromEnvironment function to determine proxies.")
    proxy_url: Optional[URL] = None
    __properties: ClassVar[List[str]] = ["no_proxy", "proxy_connect_header", "proxy_from_environment", "proxy_url"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProxyConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of proxy_url
        if self.proxy_url:
            _dict['proxy_url'] = self.proxy_url.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ProxyConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "no_proxy": obj.get("no_proxy"),
            "proxy_connect_header": obj.get("proxy_connect_header"),
            "proxy_from_environment": obj.get("proxy_from_environment"),
            "proxy_url": URL.from_dict(obj.get("proxy_url")) if obj.get("proxy_url") is not None else None
        })
        return _obj


