# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
from grafanaApiClient.models.email_dto import EmailDTO
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PublicDashboard(BaseModel):
    """
    PublicDashboard
    """ # noqa: E501
    access_token: Optional[StrictStr] = Field(default=None, alias="accessToken")
    annotations_enabled: Optional[StrictBool] = Field(default=None, alias="annotationsEnabled")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    created_by: Optional[StrictInt] = Field(default=None, alias="createdBy")
    dashboard_uid: Optional[StrictStr] = Field(default=None, alias="dashboardUid")
    is_enabled: Optional[StrictBool] = Field(default=None, alias="isEnabled")
    recipients: Optional[List[EmailDTO]] = None
    share: Optional[StrictStr] = None
    time_selection_enabled: Optional[StrictBool] = Field(default=None, alias="timeSelectionEnabled")
    uid: Optional[StrictStr] = None
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    updated_by: Optional[StrictInt] = Field(default=None, alias="updatedBy")
    __properties: ClassVar[List[str]] = ["accessToken", "annotationsEnabled", "createdAt", "createdBy", "dashboardUid", "isEnabled", "recipients", "share", "timeSelectionEnabled", "uid", "updatedAt", "updatedBy"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PublicDashboard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recipients (list)
        _items = []
        if self.recipients:
            for _item in self.recipients:
                if _item:
                    _items.append(_item.to_dict())
            _dict['recipients'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PublicDashboard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessToken": obj.get("accessToken"),
            "annotationsEnabled": obj.get("annotationsEnabled"),
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "dashboardUid": obj.get("dashboardUid"),
            "isEnabled": obj.get("isEnabled"),
            "recipients": [EmailDTO.from_dict(_item) for _item in obj.get("recipients")] if obj.get("recipients") is not None else None,
            "share": obj.get("share"),
            "timeSelectionEnabled": obj.get("timeSelectionEnabled"),
            "uid": obj.get("uid"),
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": obj.get("updatedBy")
        })
        return _obj


