# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TLSConfig(BaseModel):
    """
    TLSConfig
    """ # noqa: E501
    ca: Optional[StrictStr] = Field(default=None, description="Text of the CA cert to use for the targets.")
    ca_file: Optional[StrictStr] = Field(default=None, description="The CA cert to use for the targets.")
    cert: Optional[StrictStr] = Field(default=None, description="Text of the client cert file for the targets.")
    cert_file: Optional[StrictStr] = Field(default=None, description="The client cert file for the targets.")
    insecure_skip_verify: Optional[StrictBool] = Field(default=None, description="Disable target certificate validation.")
    key: Optional[StrictStr] = None
    key_file: Optional[StrictStr] = Field(default=None, description="The client key file for the targets.")
    max_version: Optional[StrictInt] = None
    min_version: Optional[StrictInt] = None
    server_name: Optional[StrictStr] = Field(default=None, description="Used to verify the hostname for the targets.")
    __properties: ClassVar[List[str]] = ["ca", "ca_file", "cert", "cert_file", "insecure_skip_verify", "key", "key_file", "max_version", "min_version", "server_name"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TLSConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TLSConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ca": obj.get("ca"),
            "ca_file": obj.get("ca_file"),
            "cert": obj.get("cert"),
            "cert_file": obj.get("cert_file"),
            "insecure_skip_verify": obj.get("insecure_skip_verify"),
            "key": obj.get("key"),
            "key_file": obj.get("key_file"),
            "max_version": obj.get("max_version"),
            "min_version": obj.get("min_version"),
            "server_name": obj.get("server_name")
        })
        return _obj


