# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpdateAlertNotificationWithUidCommand(BaseModel):
    """
    UpdateAlertNotificationWithUidCommand
    """ # noqa: E501
    disable_resolve_message: Optional[StrictBool] = Field(default=None, alias="disableResolveMessage")
    frequency: Optional[StrictStr] = None
    is_default: Optional[StrictBool] = Field(default=None, alias="isDefault")
    name: Optional[StrictStr] = None
    secure_settings: Optional[Dict[str, StrictStr]] = Field(default=None, alias="secureSettings")
    send_reminder: Optional[StrictBool] = Field(default=None, alias="sendReminder")
    settings: Optional[Union[str, Any]] = None
    type: Optional[StrictStr] = None
    uid: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["disableResolveMessage", "frequency", "isDefault", "name", "secureSettings", "sendReminder", "settings", "type", "uid"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpdateAlertNotificationWithUidCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpdateAlertNotificationWithUidCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disableResolveMessage": obj.get("disableResolveMessage"),
            "frequency": obj.get("frequency"),
            "isDefault": obj.get("isDefault"),
            "name": obj.get("name"),
            "secureSettings": obj.get("secureSettings"),
            "sendReminder": obj.get("sendReminder"),
            "settings": obj.get("settings"),
            "type": obj.get("type"),
            "uid": obj.get("uid")
        })
        return _obj


