server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # local machine logs
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "logstream"
      - source_labels: ["__meta_docker_container_label_logging_jobname"]
        target_label: "job"

  # syslog target
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ["__syslog_message_hostname"]
        target_label: "host"

  # - job_name: containers
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: containerlogs
  #         __path__: /var/lib/docker/containers/*/*log

  #   pipeline_stages:
  #     - json:
  #         expressions:
  #           output: log
  #           stream: stream
  #           attrs:
  #     - json:
  #         expressions:
  #           tag:
  #         source: attrs
  #     - regex:
  #         expression: (?P<container_name>(?:[^|]*[^|]))
  #         source: tag
  #     - timestamp:
  #         format: RFC3339Nano
  #         source: time
  #     - labels:
  #         # tag:
  #         stream:
  #         container_name:
  #     - output:
  #         source: output
